language: rust

cache:
  - cargo: true
  - directories:
      - ./travis/mongodb/

before_install:
    - ./script/install_mongo_release $TRAVIS_OS_NAME $MONGODB_RELEASE

script:
    - cargo test --features ssl --verbose
