language: rust

cache: cargo

env:
  global:
    # Use a global cache to re-use dependencies across release builds; downloading a mongodb release is quick.
    - CACHE_NAME=global_cache
    - RELEASE_CACHE=travis/mongodb
  matrix:
    - MONGODB_RELEASE=mongodb-linux-x86_64-ubuntu1204-3.0.14
    - MONGODB_RELEASE=mongodb-linux-x86_64-ubuntu1204-3.2.12
    - MONGODB_RELEASE=mongodb-linux-x86_64-ubuntu1204-3.4.2

before_install:
    - ./script/before_install

script:
    - ./script/script
